# Database settings.
# We've switched from SQLite.  SQLite is an excellent single-user database,
# but PostgreSQL is a better match for our production environment.
# In addition, for debugging it's best to minimize the differences between
# the development and production environments.
#
# The 'pool' parameter is important for performance on Heroku; see:
# https://devcenter.heroku.com/articles/concurrency-and-database-connections
# It can be controlled by setting the environment variable DB_POOL.
# In practice, you typically will want RAILS_MAX_THREADS + 1 for this app,
# because in addition to every web thread we occasionally fire a task to
# process occasional requests (such as the daily task).
# If RAILS_MAX_THREADS is not set, presume it is 5.
# Note double quotes on env variables to work around issue #753
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= (ENV["DB_POOL"] ||
             ((ENV["RAILS_MAX_THREADS"] || 5 ).to_i + 1)).to_i %>
  timeout: 5000

development:
  <<: *default
  database: development

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: test

# On production systems (e.g., Heroku)
# the settings are merged from this file and DATABASE_URL.
# We primarily use the values in DATABASE_URL, since that enables
# easy per-system configuration.
#
production:
  <<: *default
#  database: production

fake_production:
  <<: *default
  database: development
